#!/usr/bin/env python3
"""
tallkitchen_safety — Cross-pillar safety module for Hunt ↔ Water integration

Both pillars import this module. It encodes the rules that prevent the
closed-loop feedback amplification documented in OWASP Agentic AI Top 10 2026
(ASI06 Memory Poisoning, ASI08 Cascading Failures) — the failure mode where
two AI-using systems amplify each other's errors via shared state.

Defense layers applied (cross-pillar surface only — each pillar has its own
intra-system defenses):

  Layer 1 (Input validation)        — validate_hunt_record_for_water()
  Layer 2 (Provenance tracking)     — tag_provenance(), record source/trust
  Layer 3 (Confidence thresholds)   — should_water_act_on_hunt()
  Layer 4 (Reasoning trace)         — preserved in tag_provenance() audit fields
  Layer 5 (Human-in-the-loop)       — pending_review status on triggered rules
  Layer 6 (Output sanitization)     — done in Water's existing validate_rule
  Layer 7 (Rate limiting)           — RateLimiter, max N triggers/day
  Layer 8 (Anomaly / disagreement)  — cross_pillar_disagreement_check()

CRITICAL: The single most important rule — Water never reads records where
source == "water". Without this guard, the closed loop becomes a runaway
feedback amplifier ("one agent generates a misclassification, and the
other treats it as verified truth, leading to a feedback loop in which
the error becomes stronger with each iteration" — Knostic, Jan 2026).
"""

import json
from dataclasses import dataclass
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional


# ── Module constants ──────────────────────────────────────────────────────────

# State directory for cross-pillar coordination (rate limits, audit logs)
SAFETY_STATE_DIR = Path("state/tallkitchen")

# How fresh a verdict must be for Water to act on it. Older verdicts may
# reflect an attacker who has moved on, or stale source data.
HUNT_VERDICT_MAX_AGE_HOURS = 24

# Score threshold below which Water never acts on a verdict, regardless of
# what label Hunt assigned. Calibrated to Mandiant-style thresholds where
# 60-80 is "suspicious" and 80+ is "malicious" — we want to act on the
# upper portion of suspicious and all of malicious.
WATER_ACTION_MIN_SCORE = 75

# Verdict labels Water will consider acting on. "unknown" and "benign" never trigger.
WATER_ACTION_VERDICTS = {"suspicious", "malicious"}

# How many Water rules can be triggered by Hunt verdicts per UTC day. Hard cap.
# Even if 100 verdicts hit malicious, Water generates at most this many rules.
HUNT_TRIGGERED_DAILY_LIMIT = 5

# Trust levels for records — Water only acts on "user" source records with
# "high" trust level. Records auto-generated by either pillar get lower trust.
TRUST_LEVEL_HIGH = "high"
TRUST_LEVEL_MEDIUM = "medium"
TRUST_LEVEL_LOW = "low"
TRUST_LEVEL_QUARANTINED = "quarantined"  # known-bad, never act

# Source tags — the most critical field. Water filters out source=="water" to
# prevent the feedback loop where Water's own outputs become its inputs.
SOURCE_USER = "user"        # initiated by analyst (Hunt CLI invocation)
SOURCE_HUNT = "hunt"        # Hunt automation (alert ingestion, future)
SOURCE_WATER = "water"      # Water itself — Water MUST NOT read its own records
SOURCE_SYSTEM = "system"    # automated infrastructure (e.g. scheduled refresh)


# ── Schema validation (Layer 1) ───────────────────────────────────────────────

REQUIRED_VERDICT_FIELDS = {
    "ioc", "ioc_type", "timestamp_utc", "verdict",
}


@dataclass
class ValidationResult:
    """Result of a safety check. Always carries a reason so caller can log it."""
    passed: bool
    reason: str


def validate_hunt_record_for_water(record: dict) -> ValidationResult:
    """
    Strict schema check before Water acts on anything from tk-hunt-logs.

    A malformed or unexpected record never reaches Water's action layer.
    This is the perimeter guard — even if ES is compromised or someone
    inserts crafted records, this gate rejects anything that doesn't match
    the expected schema.

    The schema is intentionally narrow: we'd rather reject a borderline
    valid record than let a poisoned one through.
    """
    if not isinstance(record, dict):
        return ValidationResult(False, f"record is not a dict: {type(record).__name__}")

    missing = REQUIRED_VERDICT_FIELDS - record.keys()
    if missing:
        return ValidationResult(False, f"missing required fields: {sorted(missing)}")

    # The verdict bucket should be a dict with the score and label
    verdict = record.get("verdict")
    if isinstance(verdict, dict):
        # Hunt's actual write shape: result.verdict is a nested dict
        score = verdict.get("score")
        label = verdict.get("verdict")
    else:
        # Tolerate flat shape too
        score = record.get("score")
        label = verdict

    if not isinstance(score, (int, float)):
        return ValidationResult(False, f"score is not numeric: {type(score).__name__}")
    if not (0 <= score <= 100):
        return ValidationResult(False, f"score out of range [0,100]: {score}")

    if label not in {"benign", "unknown", "suspicious", "malicious"}:
        return ValidationResult(False, f"unrecognized verdict label: {label!r}")

    # Timestamp must be parseable and recent enough to be actionable
    ts = record.get("timestamp_utc")
    if not isinstance(ts, str):
        return ValidationResult(False, f"timestamp_utc is not a string: {type(ts).__name__}")
    try:
        ts_dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
    except ValueError as e:
        return ValidationResult(False, f"timestamp_utc unparseable: {e}")

    age = datetime.now(timezone.utc) - ts_dt
    if age > timedelta(hours=HUNT_VERDICT_MAX_AGE_HOURS):
        return ValidationResult(False, f"verdict too old: {age.total_seconds()/3600:.1f}h > {HUNT_VERDICT_MAX_AGE_HOURS}h")
    if age < timedelta(seconds=-60):  # allow 60s of clock skew
        return ValidationResult(False, f"verdict timestamp is in the future: {ts}")

    return ValidationResult(True, "ok")


# ── Provenance tracking (Layer 2) ─────────────────────────────────────────────

def tag_provenance(
    record: dict,
    source: str,
    trust_level: str = TRUST_LEVEL_MEDIUM,
    triggered_by_hunt_id: Optional[str] = None,
    verifier_id: Optional[str] = None,
) -> dict:
    """
    Stamp a record with provenance metadata. Returns the record (mutated in place).

    Every cross-pillar object gets these fields so downstream consumers can
    audit: where did this come from? was it user-initiated or auto-generated?
    is it trusted? does it have a verifier signature?

    triggered_by_hunt_id is critical for hunt-driven Water rules — every rule
    generated from a Hunt verdict carries the hunt_id that triggered it,
    creating an auditable chain: hunt -> verdict -> rule generation.
    """
    if source not in {SOURCE_USER, SOURCE_HUNT, SOURCE_WATER, SOURCE_SYSTEM}:
        raise ValueError(f"unknown source: {source!r}")
    if trust_level not in {TRUST_LEVEL_HIGH, TRUST_LEVEL_MEDIUM, TRUST_LEVEL_LOW, TRUST_LEVEL_QUARANTINED}:
        raise ValueError(f"unknown trust_level: {trust_level!r}")

    provenance = record.get("provenance", {}) or {}
    provenance.update({
        "source": source,
        "trust_level": trust_level,
        "tagged_at": datetime.now(timezone.utc).isoformat(),
    })
    if triggered_by_hunt_id is not None:
        provenance["triggered_by_hunt_id"] = triggered_by_hunt_id
    if verifier_id is not None:
        provenance["verifier_id"] = verifier_id

    record["provenance"] = provenance
    return record


# ── Confidence gate (Layer 3) — THE critical safety check ─────────────────────

def should_water_act_on_hunt(record: dict) -> ValidationResult:
    """
    The single most important function in this module.

    Returns (True, "ok") only if Water should generate a Sigma rule based on
    this Hunt verdict. ALL conditions must hold:

      1. Schema validates (Layer 1)
      2. provenance.source != "water"  — prevents feedback loop
      3. provenance.source in {"user", "hunt"}  — only act on legitimate inputs
      4. provenance.trust_level == "high"  — quarantined/low-trust never act
      5. verdict.score >= 75 (suspicious-upper or malicious)
      6. verdict.verdict in {"suspicious", "malicious"}
      7. verdict.conflicts == [] (no unresolved cross-source disagreement)
      8. NOT verdict.safety_brake (RIOT/benign anti-signal didn't fire)

    Every "no" returns a specific reason. The caller logs it. Audit-friendly.
    """
    # Step 1: schema
    schema_check = validate_hunt_record_for_water(record)
    if not schema_check.passed:
        return ValidationResult(False, f"schema: {schema_check.reason}")

    prov = record.get("provenance", {}) or {}
    source = prov.get("source")
    trust = prov.get("trust_level")

    # Step 2: CRITICAL — never act on Water's own outputs
    if source == SOURCE_WATER:
        return ValidationResult(False, "source=water: refusing to act on own output (prevents feedback loop)")

    # Step 3: only user-driven or hunt-automation sources
    if source not in {SOURCE_USER, SOURCE_HUNT}:
        return ValidationResult(False, f"source={source!r}: only user/hunt sources may trigger Water")

    # Step 4: trust level
    if trust != TRUST_LEVEL_HIGH:
        return ValidationResult(False, f"trust_level={trust!r}: need {TRUST_LEVEL_HIGH!r}")

    # Step 5+6: get the verdict (nested or flat shape)
    verdict = record.get("verdict")
    if isinstance(verdict, dict):
        score = verdict.get("score", 0)
        label = verdict.get("verdict")
        conflicts = verdict.get("conflicts", []) or []
        safety_brake = verdict.get("safety_brake", False)
    else:
        score = record.get("score", 0)
        label = verdict
        conflicts = record.get("conflicts", []) or []
        safety_brake = record.get("safety_brake", False)

    if score < WATER_ACTION_MIN_SCORE:
        return ValidationResult(False, f"score={score} < {WATER_ACTION_MIN_SCORE}")

    if label not in WATER_ACTION_VERDICTS:
        return ValidationResult(False, f"verdict={label!r} not in {sorted(WATER_ACTION_VERDICTS)}")

    # Step 7: cross-source disagreement is a hard stop
    if conflicts:
        return ValidationResult(False, f"unresolved conflicts ({len(conflicts)}): {conflicts[0][:100]}")

    # Step 8: if the safety brake fired (e.g. GreyNoise RIOT), don't act
    if safety_brake:
        return ValidationResult(False, "safety brake applied to verdict (high-confidence anti-signal present)")

    return ValidationResult(True, "ok")


# ── Rate limiting (Layer 7) ───────────────────────────────────────────────────

class RateLimiter:
    """
    Hard daily cap on hunt-triggered Water actions. Persisted across runs so
    the cap survives process restarts. UTC-based day boundaries.

    Usage:
        limiter = RateLimiter("hunt_triggered_rules")
        if limiter.can_consume():
            limiter.consume()
            ... do the thing ...
        else:
            ... log and skip ...
    """

    def __init__(self, name: str, daily_limit: int = HUNT_TRIGGERED_DAILY_LIMIT):
        self.name = name
        self.daily_limit = daily_limit
        SAFETY_STATE_DIR.mkdir(parents=True, exist_ok=True)
        self.state_file = SAFETY_STATE_DIR / f"ratelimit_{name}.json"

    def _today_key(self) -> str:
        return datetime.now(timezone.utc).strftime("%Y-%m-%d")

    def _load(self) -> dict:
        if not self.state_file.exists():
            return {}
        try:
            return json.loads(self.state_file.read_text())
        except (json.JSONDecodeError, OSError):
            return {}

    def _save(self, state: dict) -> None:
        self.state_file.write_text(json.dumps(state, indent=2))

    def current_count(self) -> int:
        """Count consumed slots for today (UTC)."""
        state = self._load()
        return state.get(self._today_key(), 0)

    def can_consume(self) -> bool:
        return self.current_count() < self.daily_limit

    def consume(self, n: int = 1) -> bool:
        """Atomically increment if room available. Returns True if consumed."""
        state = self._load()
        today = self._today_key()
        used = state.get(today, 0)
        if used + n > self.daily_limit:
            return False
        state[today] = used + n
        # Garbage-collect entries older than 30 days to keep file small
        cutoff = (datetime.now(timezone.utc) - timedelta(days=30)).strftime("%Y-%m-%d")
        state = {k: v for k, v in state.items() if k >= cutoff}
        self._save(state)
        return True

    def remaining(self) -> int:
        return max(0, self.daily_limit - self.current_count())


# ── Cross-pillar disagreement detection (Layer 8) ─────────────────────────────

def cross_pillar_disagreement_check(
    verdict_record: dict,
    existing_rules: list = None,
) -> list:
    """
    Identify conflicts between a Hunt verdict and Water's existing rules.

    Returns a list of human-readable conflict notes. Empty list means no
    cross-pillar disagreement. Called BEFORE Water acts on a verdict so the
    analyst (via Water's email) can see if a planned action would contradict
    something Water already knows.

    Currently checks:
      - Verdict says malicious, but a Water rule explicitly whitelists this IOC
      - Verdict's verifier disagrees with majority of Water's 3-AI validators

    Designed to extend — more conflict types can be added without changing
    the signature.
    """
    conflicts = []
    existing_rules = existing_rules or []

    ioc = verdict_record.get("ioc")
    if not ioc:
        return conflicts

    verdict = verdict_record.get("verdict")
    label = verdict.get("verdict") if isinstance(verdict, dict) else verdict

    if label == "malicious":
        for rule in existing_rules:
            # Whitelist rules typically have a special title/tag
            rule_title = (rule.get("title") or "").lower()
            rule_tags = rule.get("tags") or []
            is_whitelist = (
                "whitelist" in rule_title
                or "allowlist" in rule_title
                or any("whitelist" in (t or "").lower() for t in rule_tags)
            )
            if is_whitelist:
                # Does the whitelist rule reference this IOC?
                rule_text = json.dumps(rule, default=str).lower()
                if ioc.lower() in rule_text:
                    conflicts.append(
                        f"Hunt says malicious but Water rule {rule.get('id', '?')[:8]} "
                        f"explicitly whitelists this IOC"
                    )

    return conflicts


# ── Convenience: end-to-end safety decision ───────────────────────────────────

def water_should_generate_rule_from_verdict(
    record: dict,
    existing_rules: list = None,
    rate_limiter: "RateLimiter" = None,
) -> ValidationResult:
    """
    Composite check used by Water's main loop. Bundles every gate into one
    call so the integration code can stay simple:

        result = water_should_generate_rule_from_verdict(record, rules, limiter)
        if result.passed:
            ... generate rule ...
        else:
            log.info(f"skipping {record['ioc']}: {result.reason}")

    All gates run in cheap-first order so we fail fast.
    """
    # Cheap gate first: confidence + provenance
    gate = should_water_act_on_hunt(record)
    if not gate.passed:
        return gate

    # Rate limit next (still cheap — single file read)
    if rate_limiter is not None and not rate_limiter.can_consume():
        return ValidationResult(False, f"daily rate limit exhausted ({rate_limiter.daily_limit}/day)")

    # Cross-pillar disagreement last (potentially scans existing rules)
    disagreements = cross_pillar_disagreement_check(record, existing_rules)
    if disagreements:
        return ValidationResult(False, f"cross-pillar conflict: {disagreements[0]}")

    return ValidationResult(True, "ok")


# ── Self-test when run directly ───────────────────────────────────────────────

if __name__ == "__main__":
    """
    Run as: python tallkitchen_safety.py
    Exercises every gate with synthetic records. Useful as a smoke test
    after edits and as living documentation of what each gate does.
    """
    import sys

    def _expect(actual: ValidationResult, expected_passed: bool, label: str) -> bool:
        ok = actual.passed == expected_passed
        symbol = "✓" if ok else "✗"
        print(f"  {symbol} {label}: passed={actual.passed} reason={actual.reason!r}")
        return ok

    all_ok = True
    now = datetime.now(timezone.utc).isoformat()

    print("== Schema validation ==")
    all_ok &= _expect(
        validate_hunt_record_for_water({}),
        False, "empty dict rejected"
    )
    all_ok &= _expect(
        validate_hunt_record_for_water({
            "ioc": "1.2.3.4", "ioc_type": "ipv4", "timestamp_utc": now,
            "verdict": {"score": 75, "verdict": "suspicious"},
        }),
        True, "minimal valid record"
    )
    all_ok &= _expect(
        validate_hunt_record_for_water({
            "ioc": "1.2.3.4", "ioc_type": "ipv4", "timestamp_utc": now,
            "verdict": {"score": 150, "verdict": "suspicious"},
        }),
        False, "out-of-range score rejected"
    )
    old_ts = (datetime.now(timezone.utc) - timedelta(hours=48)).isoformat()
    all_ok &= _expect(
        validate_hunt_record_for_water({
            "ioc": "1.2.3.4", "ioc_type": "ipv4", "timestamp_utc": old_ts,
            "verdict": {"score": 90, "verdict": "malicious"},
        }),
        False, "too-old record rejected"
    )

    print("\n== Action gate ==")
    good_record = {
        "ioc": "77.83.240.70", "ioc_type": "ipv4", "timestamp_utc": now,
        "verdict": {"score": 90, "verdict": "malicious", "conflicts": []},
        "provenance": {"source": SOURCE_USER, "trust_level": TRUST_LEVEL_HIGH},
    }
    all_ok &= _expect(
        should_water_act_on_hunt(good_record),
        True, "user+high+score90+malicious -> ACT"
    )
    water_source = dict(good_record)
    water_source["provenance"] = {"source": SOURCE_WATER, "trust_level": TRUST_LEVEL_HIGH}
    all_ok &= _expect(
        should_water_act_on_hunt(water_source),
        False, "source=water -> REFUSE (feedback loop guard)"
    )
    low_trust = dict(good_record)
    low_trust["provenance"] = {"source": SOURCE_USER, "trust_level": TRUST_LEVEL_LOW}
    all_ok &= _expect(
        should_water_act_on_hunt(low_trust),
        False, "low trust -> REFUSE"
    )
    low_score = dict(good_record)
    low_score["verdict"] = {"score": 65, "verdict": "suspicious", "conflicts": []}
    all_ok &= _expect(
        should_water_act_on_hunt(low_score),
        False, "score 65 (below 75 threshold) -> REFUSE"
    )
    with_conflicts = dict(good_record)
    with_conflicts["verdict"] = {
        "score": 90, "verdict": "malicious",
        "conflicts": ["GreyNoise benign vs AbuseIPDB 90/100"]
    }
    all_ok &= _expect(
        should_water_act_on_hunt(with_conflicts),
        False, "conflicts present -> REFUSE"
    )
    safety_brake_record = dict(good_record)
    safety_brake_record["verdict"] = {
        "score": 75, "verdict": "suspicious", "conflicts": [], "safety_brake": True
    }
    all_ok &= _expect(
        should_water_act_on_hunt(safety_brake_record),
        False, "safety brake fired -> REFUSE"
    )

    print("\n== Rate limiter ==")
    # Use a test-only limiter that doesn't pollute real state
    test_state = SAFETY_STATE_DIR / "ratelimit_test_selftest.json"
    if test_state.exists():
        test_state.unlink()
    limiter = RateLimiter("test_selftest", daily_limit=2)
    assert limiter.can_consume(), "limiter should start fresh"
    assert limiter.consume(), "first consume should succeed"
    assert limiter.consume(), "second consume should succeed"
    assert not limiter.can_consume(), "third can_consume should fail"
    assert not limiter.consume(), "third consume should fail"
    assert limiter.remaining() == 0, "remaining should be 0"
    print(f"  ✓ rate limiter: 2/2 consumed, 3rd refused, remaining=0")
    # Clean up
    if test_state.exists():
        test_state.unlink()

    print("\n== Cross-pillar disagreement ==")
    whitelisted = cross_pillar_disagreement_check(
        good_record,
        existing_rules=[{
            "id": "abc12345-...",
            "title": "Internal whitelist for known-good infra",
            "tags": ["whitelist"],
            "detection": {"selection": {"src_ip": "77.83.240.70"}},
        }]
    )
    print(f"  {'✓' if whitelisted else '✗'} whitelist conflict surfaced: {whitelisted}")
    all_ok &= bool(whitelisted)

    print("\n== Composite ==")
    limiter2 = RateLimiter("test_composite", daily_limit=5)
    composite = water_should_generate_rule_from_verdict(good_record, [], limiter2)
    all_ok &= _expect(composite, True, "good record passes composite")
    test_state2 = SAFETY_STATE_DIR / "ratelimit_test_composite.json"
    if test_state2.exists():
        test_state2.unlink()

    print()
    if all_ok:
        print("ALL CHECKS PASSED")
        sys.exit(0)
    else:
        print("SOME CHECKS FAILED")
        sys.exit(1)
